### ISSUE TITLE
Format deletes BUILD file if invalid

### ISSUE THREAD

**Issue by silvergasp** [bazelbuild/vscode-bazel#123]
I have a problem where formatting of BUILD files using buildifier completely deletes the entire contents of the BUILD file. This is specifically when the syntax of the build file is incorrect. 

vscode-bazel version: 0.2.0
buildifier version: latest (git commit baa9c57c396019f0b7272b95d66f8e2681ed7d2a)

Steps to reproduce; 
1. Create invalid BUILD file 
2. Right click in the text editor window, then choose "Format document" (ctrl+shift+i)

**Comment by allevato** [comment]
I believe this should be fixed by https://github.com/bazelbuild/vscode-bazel/commit/5dd591abf896719980e8652a1f2f3f74c0a959b3, which was committed about a month ago but we haven't cut a release since then.

If you're willing, you can try building the extension from source and seeing if it resolves your issue; we'll try to cut a release soon that includes the fix in the meantime.

**Comment by allevato** [comment]
The 0.3.0 release should contain the fix mentioned above. Please re-open if you run into other issues!
