### ISSUE TITLE
update quick pick query engine for large workspaces 

### ISSUE THREAD

**Issue by jeffbean** [bazelbuild/vscode-bazel#133]
Having a massive bazel ecosystem running `kind('.* rule', ...)` is quite expensive and slow.

I would like to add a way to detect the current subtree in the target graph and add this context to the queries. 

## proposed updates to the picking query engine

`bazel query "kind('.* rule', //src/subdir/...)"`

OR run the command in the CWD of the file we are active on

`PWD=src/subdir bazel query "kind('.* rule', ...)"`

**Comment by thomasvl** [comment]
You might want to look at #83, if the quick pick only use the same options as the tree view, you might not have as many issues.

**Comment by thomasvl** [comment]
Just trimming where the quickpick roots from won't completely fix this for large repos.  No matter what we pick, it could still have to query a whole lot of things.  Rooting the query to the dir the active editor is won't help for people that put sources in sub dirs of a package (models vs. views, etc.); they likely would have a cwd that doesn't even have a BUILD file.

Anyway, opened #162 opened for the general support for large repos since it is more than just the quickpicks that can suffer.

**Comment by thomasvl** [comment]
Closing this out with #163 having hopefully helped and and #162 being open for the general issues with large workspaces.
