### ISSUE TITLE
Build script is broken

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/vscode-bazel#252]
I created https://github.com/bazelbuild/vscode-bazel/releases/tag/0.5.0 for the next release.

The release instructions tell me to run

````
npm install -g vsce
vsce package
````

However, the second command leads to

````
xargs: ./node_modules/protobufjs/bin/pbjs: No such file or directory
npm ERR! code 127
npm ERR! path /Users/fwe/vscode-bazel
npm ERR! command failed
npm ERR! command sh -c ./scripts/build.sh
````

I'm not really familiar with npm, and some googling led me to install some packages (pbjs, protobufjs), but without success.

**Comment by jfirebaugh** [comment]
This seems to be fixed. `vsce package` currently completes without error.

**Comment by fweikert** [comment]
Based on the code it should be `[...]/protobufjs-cli/[...]` now, right?

**Comment by jfirebaugh** [comment]
Where do you see `protobufjs-cli`?

I see:

https://github.com/bazelbuild/vscode-bazel/blob/a0101daa091ad61b714e5bce0e90f72bf03c0e7d/scripts/build.sh#L23-L24

Which matches:

https://github.com/bazelbuild/vscode-bazel/blob/a0101daa091ad61b714e5bce0e90f72bf03c0e7d/package.json#L379-L379

And `node_modules/protobufjs/cli/bin/{pbts,pbjs}` does exist for me.

The script [can be simplified](https://github.com/bazelbuild/vscode-bazel/pull/280) to just use unqualified `pbjs`, `pbts`, and `tsc` commands, because it runs as an npm script, which has `node_modules/.bin` on the path. But it also works in its current form for me.

**Comment by fweikert** [comment]
Thanks, I think I somehow screwed up the versions of my dependencies, since I didn't find the binaries in protobufjs (and thus had to install protobufjs-cli). Will try again from a clean slate.

**Comment by fweikert** [comment]
Thanks for simplifying the script!
