### ISSUE TITLE
Bazel CI is failing since February 2022

### ISSUE THREAD

**Issue by limdor** [bazelbuild/vscode-bazel#269]
Having the CI red might stop people from contributing because they do not know if with their PR they might be breaking somethin.
Below the error message can be found.
The interesting part is that from the last green, no commit has been added. I guess something from the infrastructure has changed.

<html>
<body>

bazel info output_base
--
  | 2022/07/24 00:04:39 Downloading https://releases.bazel.build/5.2.0/release/bazel-5.2.0-linux-x86_64...
  | WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
  | Extracting Bazel installation...
  | ERROR: The 'info' command is only supported from within a workspace (below a directory having a WORKSPACE file).
  | See documentation at https://docs.bazel.build/versions/main/build-ref.html#workspace
  | Traceback (most recent call last):
  | File "bazelci.py", line 3659, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 3639, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 1282, in execute_commands
  | os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary, platform)
  | File "bazelci.py", line 1951, in get_output_base
  | print_output=False,
  | File "bazelci.py", line 2273, in execute_command_and_get_output
  | universal_newlines=True,
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['bazel', 'info', 'output_base']' returned non-zero exit status 2.
  | 🚨 Error: The command exited with status 1
  | user command error: The plugin docker command hook exited with status 1

</body>
</html>

**Comment by fweikert** [comment]
The culprit is https://github.com/bazelbuild/continuous-integration/pull/1331

Some context:

Our CI infra expects all projects to be buildable with Bazel, i.e. there must be a WORKSPACE file and at least one BUILD file.
This project did not meet this requirement, but we still wanted to run it on CI. Someone came up with a workaround: Let's create dummy WORKSPACE and BUILD files during setup ("shell_commands"). However, this stopped working because https://github.com/bazelbuild/continuous-integration/pull/1331 changed the CI infra to run `bazel info` before executing the shell commands, which then failed because there was no Bazel workspace yet.
