### ISSUE TITLE
Add buildifier support

### ISSUE THREAD

**Issue by allevato** [bazelbuild/vscode-bazel#27]
Even in the absence of a full language server (#1), we should add support for `buildifier` to surface lint warnings in the editor and support `--fix` mode as a formatting action.

**Comment by thomasvl** [comment]
Buildifier does two classes of things:

* `--mode=file` will cause it to reformat the file.  Likely want to support that for auto format on save.
* `--lint=(warn|fix)` is a replacement for skylint.  There is a subtly here, not everything generated by `--lint=warn` also can be fixed by the tool.  So I'm not sure if it makes sense to support `--lint=fix` on save or just bumble up the warning results into the UI while editing/etc.

**Comment by allevato** [comment]
This was fixed by #33.
