### ISSUE TITLE
Build extension with Bazel

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/vscode-bazel#293]
I've been looking for a way to build vscode plugins with Bazel. I think it'd be a good improvement and very helpful to the community if rules were written to build this plugin using Bazel so others can see a concrete example of how to do so.

**Comment by cameron-martin** [comment]
I've had a look into this, and the first hurdle I encountered was the packaging of vsix files. Since these are just zips, it makes sense to use rules_pkg for this. These are mainly just the compiled JS files, package.json, etc, but they do include some generated metadata files which I guess we'd need to generate using [vscode-vsce](https://github.com/microsoft/vscode-vsce) as a library.

**Comment by cameron-martin** [comment]
Duplicate of #293
