### ISSUE TITLE
Marketplace release for v0.10.0

### ISSUE THREAD

**Issue by ryanwilsonperkin** [bazelbuild/vscode-bazel#385]
[v0.10.0](https://github.com/bazelbuild/vscode-bazel/releases/tag/0.10.0) has been released, but doesn't appear to be available on the VSCode marketplace https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel
 
 Flagging because it looks like it might have been an issue with the GitHub action for releases not working correctly

**Comment by vogelsgesang** [comment]
Yes, we are aware of this. The marketplace listing is owned by Google. @cameron-martin already reached out to them, and asked for the new version to be published. Afaik, we did not hear back, yet

**Comment by steeve** [comment]
Thanks for the response, I was frantically refreshing the marketplace.
Does this mean the project has changed hands ?

**Comment by vogelsgesang** [comment]
The project [lay dormant for a while](https://github.com/bazelbuild/vscode-bazel/issues/241). Google is not internally using the VS Code extension and [does not have plans or capacity to invest into it](https://github.com/bazelbuild/vscode-bazel/pull/364#issuecomment-2047296455).

Recently, @cameron-martin and myself joined @jfirebaugh as maintainers. Since then, there has been more active development again, both on this extension as well as on two (experimental) language servers ([one](https://github.com/withered-magic/starpls), [two](https://github.com/cameron-martin/bazel-lsp)) for Starlark.

With the new activity of this project, we recently also saw contributions from other contributors picking up again. In case you also want to contribute, contributions are highly welcome 🙂 

Mid-term, this project will likely migrate from a `bazel-build` to a [`bazel-contrib`](https://github.com/bazel-contrib) project. (Just like [many other projects](https://github.com/orgs/bazelbuild/discussions/2)) As part of this, I hope that we will be able to also ship releases to the MarketPlace on a higher cadence, independently of Google

**Comment by vogelsgesang** [comment]
In the meantime, you can install the latest version of this extension using VS Code's "Install from VSIX" command. You can download the vsix for 0.10.0 from the [release page](https://github.com/bazelbuild/vscode-bazel/releases/tag/0.10.0) or get the latest HEAD version from the [GitHub Action](https://github.com/bazelbuild/vscode-bazel/actions/workflows/build.yml)'s artifacts

**Comment by fweikert** [comment]
0.10.0 has been published.

**Comment by vogelsgesang** [comment]
Thank you 🙂

**Comment by vogelsgesang** [comment]
@whitered-magic FYI. You might want to update your README in https://github.com/withered-magic/starpls to mention 0.10.0 instead of 0.9.0 and update the config snippet (see #369)

**Comment by vogelsgesang** [comment]
@withered-magic FYI. You might want to update your README in https://github.com/withered-magic/starpls to mention 0.10.0 instead of 0.9.0 and update the config snippet (see #369)

**Comment by withered-magic** [comment]
Done!
